version: "3.8"

services: 
   loans:
        image: eazybytes/accounts:latest
        mem_limit: 700m
        ports: 
            - 8010:8010
        networks:
            - easybank-network

    loans:
        image: eazybytes/loans:latest
        mem_limit: 700m
        ports: 
            - 8020:8020
        networks:
            - easybank-network
            
    cards:
        image: eazybytes/cards:latest
        mem_limit: 700m
        ports: 
            - 8030:8030
        networks:
            - easybank-networks
networks:
    eazybytes-network: